### ISSUE TITLE
auth session and log in not working

### ISSUE THREAD

**Issue by lacabra** [lacabra/proco-map-app#23]
When loading https://develop.projectconnect.app/, the following error appears on the browser console:

![Screen Shot 2021-02-15 at 4 40 12 PM](https://user-images.githubusercontent.com/6098973/108002351-9b919700-6fac-11eb-8bc6-c9c75ce3426b.png)

Clicking on the `Sign In` button throws the following other set of errors, and nothing happens:

![Screen Shot 2021-02-15 at 4 41 51 PM](https://user-images.githubusercontent.com/6098973/108002405-c4199100-6fac-11eb-8d73-b4fe58af71ca.png)

**Comment by lacabra** [comment]
Further inspection on `localhost` reveals the following error:

```
TypeError: Cannot read property 'type' of undefined
    at _default (proco-map-app/node_modules/next-auth/dist/adapters/typeorm/lib/transform.js:108:14)
    at Object.Adapter (proco-map-app/node_modules/next-auth/dist/adapters/typeorm/index.js:50:26)
    at __webpack_exports__.default (webpack-internal:///./pages/api/auth/[...nextauth].js:33:80)
    at apiResolver (proco-map-app/node_modules/next/dist/next-server/server/api-utils.js:8:7)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by EkkuJ** [comment]
This is a bit odd given that the previous config worked on my machine.

[https://next-auth.js.org/errors#client_fetch_error](https://next-auth.js.org/errors#client_fetch_error) suggests that there could be some issue in the DATABASE_URL env variable. Could you confirm that the DATABASE_URL for the dev-deployment looks something like `postgres://<username>/<password>@<host>:<port>/<db_name>`?

Also should be noted that as the custom adapter modifies the schema of the users-table, at least that table should be updated (deleted and created again).

**Comment by lacabra** [comment]
@EkkuJ: the `client_fetch_error` appeared to be unrelated. My local config was missing `NEXTAUTH_URL`, I added it and error went away. I also confirm that in the development/production environments on vercel.app that variable is already in place.

However, the `TypeError: Cannot read property 'type' of undefined` remained. I confirm that the changes introduced in #24 fixed the above error.
