### ISSUE TITLE
Add result page facts about user accomplishments

### ISSUE THREAD

**Issue by CallaJune** [lacabra/proco-map-app#29]
The result page includes a dynamically generated fact about the user's accomplishments, either based on all of the locations they have mapped or based on their accomplishments compared to other users. 

We will add more facts:
* If user has mapped more locations than any other user (or in top 10)
* If user has mapped more locations in a specific country than any other user (or in top 10).

Feel free to comment with additional fact ideas.

**Comment by CallaJune** [comment]
Right now I'm focusing on facts that could apply to all users rather than facts that may not apply to all users (not all users are in the top 5% in any given country). I'm going to add facts here and there while thinking about how to integrate facts that apply only to some users into the current structure.

**Comment by CallaJune** [comment]
@lacabra I think that it can. It addresses 99% of the cases where someone would be presented with the sample test again and be annoyed about it.

**Comment by lacabra** [comment]
@CallaJune It sounds you got the issues mixed up 🙃 this is not about the most recent PR you submitted (which already closed the corresponding issue), but about the result page facts about user accomplishments

**Comment by CallaJune** [comment]
Ah, yes. In that case, I think that that's all I had for facts currently, but I would like to make some more facts based on additional information, perhaps from the Project Connect map database.

**Comment by lacabra** [comment]
Understood. Closing it for now. We can open another issue/PR for additional facts once we have clarity.
