### ISSUE TITLE
Change design of sign in button

### ISSUE THREAD

**Issue by CallaJune** [lacabra/proco-map-app#35]
Current sign in button:
<img width="155" alt="Screen Shot 2021-02-18 at 10 22 11 PM" src="https://user-images.githubusercontent.com/6993618/108453092-c04d6f00-7237-11eb-825a-4ae2b8b15054.png">

New design: 
<img width="181" alt="Screen Shot 2021-02-18 at 10 22 32 PM" src="https://user-images.githubusercontent.com/6993618/108453118-cd6a5e00-7237-11eb-8791-3d98be6eac1e.png">

**Comment by lacabra** [comment]
Thanks @CallaJune. Kindly note that @EkkuJ is working on this in #31

**Comment by CallaJune** [comment]
Thanks for telling me. I'll close this issue.

**Comment by lacabra** [comment]
It's fine either way, but you could also have left it open, and it would have been closed when that PR had been merged.
