### ISSUE TITLE
Change instant user feedback design

### ISSUE THREAD

**Issue by CallaJune** [lacabra/proco-map-app#36]
Before:
<img width="544" alt="Screen Shot 2021-02-21 at 5 11 28 PM" src="https://user-images.githubusercontent.com/6993618/108640467-d772a380-7467-11eb-85aa-5ff6af8c2359.png">
<img width="562" alt="Screen Shot 2021-02-21 at 5 10 50 PM" src="https://user-images.githubusercontent.com/6993618/108640457-c0cc4c80-7467-11eb-9d25-4a084f30636e.png">

After:
<img width="239" alt="Screen Shot 2021-02-21 at 5 12 45 PM" src="https://user-images.githubusercontent.com/6993618/108640503-05f07e80-7468-11eb-9aee-9fdb0df11158.png">
or
<img width="234" alt="Screen Shot 2021-02-21 at 5 14 37 PM" src="https://user-images.githubusercontent.com/6993618/108640532-49e38380-7468-11eb-95ee-f85301adf826.png">

**Comment by lacabra** [comment]
@CallaJune I would go for the second design, if we then pair it to coloring the feedback on the responses, so that there is a 1-to-1 mapping of colors on the Yes, No, Maybe from the buttons to the feedback.

**Comment by lacabra** [comment]
Fixed in #39
