### ISSUE TITLE
Only present the test once

### ISSUE THREAD

**Issue by lacabra** [lacabra/proco-map-app#47]
Since we encourage repeated use of the app for mapping schools, we can skip the option doing the optional test under the following two conditions:
- the user has completed the test once
- the user had completed one full set of mapping schools (10)

**Comment by CallaJune** [comment]
Additionally, we could also have the "map more schools" button on the results page direct to `/mapping`.

**Comment by lacabra** [comment]
Great point, since that's a trivial change 🙃

We can implement this now, and lower the priority of implementing the rest, since it will probably address the most common use case or repeated mapping.
