### ISSUE TITLE
Styled profile page

### ISSUE THREAD

**Issue by EkkuJ** [lacabra/proco-map-app#53]
Currently the profile page is a very barebones version of the intended functionality. We should fix that.

**Now**
![Screenshot 2021-03-05 at 15 11 53](https://user-images.githubusercontent.com/57347734/110119980-20f6b300-7dc5-11eb-980a-e7d778f0c23f.png)

**Intended**
![Screenshot 2021-03-05 at 15 14 01](https://user-images.githubusercontent.com/57347734/110120214-6d41f300-7dc5-11eb-9478-f5295b200b10.png)

@CallaJune @lacabra Do we have plans to implement the level-functionality ("Bronze level" in screenshot) or the achievement-functionality soon?

**Comment by CallaJune** [comment]
At this point, we don't have plans to design or implement levels (e.g. Bronze level).

**Comment by lacabra** [comment]
Correct, but @CallaJune is already working on the achievements component.

Initial work was started in #18 and continues in #29. That is mostly focused on displaying results right after user successfully maps 10 schools, but most of that data should be reusable for the profile page.

**Comment by lacabra** [comment]
Fixed in #62
