### ISSUE TITLE
Keyboard shortcuts for desktop for faster review

### ISSUE THREAD

**Issue by lacabra** [lacabra/proco-map-app#81]
Test user @planemad suggest this new feature: 

- Keyboard shortcuts for desktop for faster review.

**Comment by vaishnavi-ch** [comment]
@lacabra though this issue is on hold, can I give it a try? (I know it might not be merged currently), or else may I know if there are any other available issues to work on?

**Comment by lacabra** [comment]
@vaishnavi-ch: Yes, you are welcome to give it a try, thank you

**Comment by vaishnavi-ch** [comment]
overview of the project -

SAME SHORTCUTS

create same shortcuts for all users (much easier) but not all have the same preferences so I dont think this is a good idea , so we can create a functionality where user can set their preferences

(OR)

DIFFERENT SHORTCUTS - In this case the preferences should be stored in the database

(ii) we can have "edit key shortcuts" option , on click it will open a popup/ modal where the user can set their preferences. The user can set shortcuts for only 4 buttons ("yes","no","unsure","next"),
so I thought a popup will be enough. But I'm not sure if the UI will look good, The provided screenshot is to show the functionality, We can make changes to the design

![image](https://user-images.githubusercontent.com/66664653/116355398-6c529e00-a817-11eb-925f-d62e5574509c.png)
![image](https://user-images.githubusercontent.com/66664653/116355944-3530bc80-a818-11eb-8929-50ad61fbfc7f.png)

(OR) 
(iii) or else we can have "edit key shortcuts" between the view profile and signout under the drop down. It takes us to a page where the user can set them.

For implementing the shortcuts part we can install "react-hotkeys-hook" as it is easy to use, If we dont want to install additional packages, then we have to create a custom hook for it.

**Comment by lacabra** [comment]
Thanks @vaishnavi-ch for presenting your proposal so clearly 🙏

* I agree that using **react-hotkeys-hook** makes the most sense. Curious to know if loading the library can be conditional on the platform, so that it doesn't even load on mobile to save bandwidth.
* I'm ok starting with (I) and set the same shortcuts for all users. I would assign ENTER to `Next`, and I'm open to figuring out the best combination for `Yes`, `No`, `Maybe`. One option would be to go with the initials `Y`, `N` and `M` but the distribution of these keys on the keyboard makes it suboptimal. The other proposal would be to assign keys that map to the layout of the buttons in terms of Left ('Z'), Center ('V'), Right ('M')

Curious to hear @planemad opinion on the mapping of keys, since he raised the original issue at unicef/projectconnect-game#11

**Comment by planemad** [comment]
Based on https://github.com/unicef/projectconnect-game/issues/13, this is what i've been using:

right : next
up: yes
down: no
left: unsure

```
function handleKeys(e){ 
e.keyCode == '38' && document.querySelectorAll('.btn-outline-primary')[0].click();
e.keyCode == '40' && document.querySelectorAll('.btn-outline-primary')[1].click();
e.keyCode == '37' && document.querySelectorAll('.btn-outline-primary')[2].click();
e.keyCode == '39' && document.querySelector('.next-section .btn-primary').click();
 }
document.addEventListener('keydown', handleKeys);
```

Can finish a batch of 10 in under 15 secs.

**Comment by vaishnavi-ch** [comment]
@lacabra ,@planemad Thank you for your suggestions, code example. However, Due to unfortunate situations, I won't be available for few days probably until May 5th, I apologize. Anyone who is interested can work on this issue.

**Comment by rachita19082** [comment]
@lacabra Since @vaishnavi-ch is not available to work on this issue, can I give it a try?

**Comment by lacabra** [comment]
@rachita19082: No, please be kind and let @vaishnavi-ch finish it. @vaishnavi-ch said would be back tomorrow, I'm ok waiting one more day. Thanks.

**Comment by rachita19082** [comment]
Okay, thanks @lacabra. Let me know if any new issues open up.

**Comment by vaishnavi-ch** [comment]
@lacabra Thank you, I'll continue working on this

**Comment by vaishnavi-ch** [comment]
Sorry for the inconvenience again, @rachita19082 you can work on this task.

**Comment by rachita19082** [comment]
@lacabra Please let me know if I should work on this issue.

**Comment by lacabra** [comment]
Yes, @rachita19082: I have assigned it to you.

Thanks @vaishnavi-ch for your contributions up to this point, much appreciated! 🙏

**Comment by rachita19082** [comment]
Thanks @lacabra, I'll start working on this.

> Based on [unicef/projectconnect-game#13](https://github.com/unicef/projectconnect-game/issues/13), this is what i've been using:
> 
> right : next
> up: yes
> down: no
> left: unsure
> 
> ```
> function handleKeys(e){ 
> e.keyCode == '38' && document.querySelectorAll('.btn-outline-primary')[0].click();
> e.keyCode == '40' && document.querySelectorAll('.btn-outline-primary')[1].click();
> e.keyCode == '37' && document.querySelectorAll('.btn-outline-primary')[2].click();
> e.keyCode == '39' && document.querySelector('.next-section .btn-primary').click();
>  }
> document.addEventListener('keydown', handleKeys);
> ```
Please confirm if I should map the keys as given here.
