### ISSUE TITLE
Header height in the post signed in state

### ISSUE THREAD

**Issue by upretiprateek** [lacabra/proco-map-app#90]
Once I sign in and go back to the landing page, the header height gets distorted.
(See attached image).

Note: this issue occurred only in the mobile website.

![WhatsApp Image 2021-04-20 at 4 16 15 PM](https://user-images.githubusercontent.com/47604754/115383681-c6d67380-a1f3-11eb-8e7c-172d12c87c0e.jpeg)

**Comment by Msgl** [comment]
Hello @lacabra ! Could you please assign this issue to me? I would like to work on it.

**Comment by lacabra** [comment]
@upretiprateek can you please provide additional details about your mobile environment? (device and operating system) Because it displays just fine on Brave on iOS, see screenshot below:

![IMG_0927](https://user-images.githubusercontent.com/6098973/115922811-99c7d200-a43a-11eb-98e6-2dd3c3938717.PNG)

**Comment by lacabra** [comment]
@Msgl, I have assigned it to you, but before you start working on this you may want to check if it's an issue on your mobile, because it displays fine (and thus it is not an issue) on my end. If we cannot identify the source of the issue that @upretiprateek reports, you may not be able to work on this at all. I suggest you alternatively look into #91

**Comment by Msgl** [comment]
@lacabra I checked the application on my mobile and it looks like @upretiprateek 's.

![Screenshot_20210423-230626_Chrome](https://user-images.githubusercontent.com/11541430/115924952-18e3f700-a489-11eb-8085-059d685654ab.jpg)

**Comment by lacabra** [comment]
Great, then you have a good issue to work on, because what you are seeing should not happen.

**Comment by Msgl** [comment]
Thank you, I will start working on it!

**Comment by Msgl** [comment]
Hello @lacabra , can you please guide me on how to log in to the application on localhost? 

Is there somewhere in the code I can find the secret mentioned in the authentication functionalities section below, or can you provide it to me? Also, how should I fill in the rest of the fields (NEXTAUTH_URL, FACEBOOK_ID etc.)?

          "To work with the authentication functionalities, you need to add the following entries to the .env or .env.local:
          SECRET="A secret to use for key generation"
          NEXTAUTH_URL="HOST_URL"
          FACEBOOK_ID="YOUR_FACEBOOK_ID"
          FACEBOOK_SECRET="YOUR_FACEBOOK_SECRET"
          TWITTER_CLIENT_ID="YOUR_TWITTER_CLIENT_ID"
          TWITTER_CLIENT_SECRET="YOUR_TWITTER_CLIENT_SECRET"
          GOOGLE_CLIENT_ID="YOUR_GOOGLE_CLIENT_ID"
          GOOGLE_CLIENT_SECRET="YOUR_GOOGLE_CLIENT_SECRET"
          NEXT_PUBLIC_AUTH_CALLBACK="HOST_URL"
          To obtain the secrets, contact one of the contributors."

**Comment by lacabra** [comment]
@Msgl I have expanded the documentation on the repo README in  be6092c, refer to the updated [Developer Environment](https://github.com/lacabra/proco-map-app/blob/master/README.md#-development-environment) section.

I can't provide you with the required credentials for security reasons, but it should be easy for you to create your own ones for GitHub, by following these instructions:
https://docs.github.com/en/developers/apps/creating-an-oauth-app

Let me know if you have further questions in this regard.

**Comment by Msgl** [comment]
@lacabra thank you!
