### ISSUE TITLE
Add Javascript linter

### ISSUE THREAD

**Issue by lacabra** [lacabra/proco-map-app#95]
Add and configure ESlint + Prettier + Husky.

If you want to propose a different setup, please discuss the details of your proposal on this issue before submitting a pull request.

Use lacabra/validate-digitalpublicgoods#14 for reference

**Comment by Rolikasi** [comment]
Hi @lacabra, kindly assign this issue to me. I want to work on it

**Comment by lacabra** [comment]
Fixed by #100
